# Generated by Django 3.2.6 on 2021-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(related_name='related_coupons', to='coupons.Coupon'),
        ),
    ]
