# Generated by Django 3.2.6 on 2021-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_order', to='orders.Order', verbose_name='Замовлення покупця'),
        ),
        migrations.AddField(
            model_name='userbase',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
