# Generated by Django 3.2.6 on 2021-09-27 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('valid_from', models.DateTimeField(verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(verbose_name='Дійсний до')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент знижки')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купони',
            },
        ),
    ]
