# Generated by Django 3.2.6 on 2021-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupons'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applied_to',
            field=models.ManyToManyField(blank=True, related_name='related_carts', to='cart.Cart'),
        ),
    ]
